### ISSUE TITLE
Trouble with setting 'humidifierFunction' 'properties/set'

### ISSUE THREAD

**Issue by aftertommy** [banban525/echonetlite2mqtt#14]
I have a Daikin うるさらx, which features a humidifier mode. In echonet lite, the humidifier mode is represented as:

```json
{
    "operationStatus":"true", 
    "operationMode":"circulation", 
    "humidifierFunction":"on"
}
```

I've created a [MQTT humidifier](https://www.home-assistant.io/integrations/humidifier.mqtt/) to control just the humidifier function:

```yaml
    - name: "Master Bedroom Humidifier"
      unique_id: "master_bedroom_humidifier"
      device:
        manufacturer: DAIKIN INDUSTRIES,LTD
        hw_version: 010c0100
        identifiers: [master_bedroom_humidifier]
        suggested_area: Master Bedroom
        name: "Master Bedroom Humidifier"
      icon: mdi:air-humidifier
      device_class: "humidifier"
      min_humidity: 50
      max_humidity: 60
      qos: 1
      state_topic: "echonetlite2mqtt/elapi/v2/devices/master_bedroom_ac/properties"
      state_value_template: >-
        {% if value_json.operationStatus == 'false' %}
          OFF
        {% elif value_json.operationMode != 'circulation' %}
          OFF
        {% elif value_json.humidifierFunction == 'on' %}
          ON
        {% else %}
          OFF
        {% endif %}
      command_topic: "echonetlite2mqtt/elapi/v2/devices/master_bedroom_ac/properties/set"
      command_template: >-
        {% if value == 'ON' %}
            {"operationStatus":"true", "operationMode":"circulation", "humidifierFunction":"on"}
        {% else %}
            {"operationStatus":"false"}
        {% endif %}
      target_humidity_state_topic: "echonetlite2mqtt/elapi/v2/devices/master_bedroom_ac/properties"
      target_humidity_state_template: >-
        {{ ((value_json.humidificationLevel + 7) * 5) }}
      target_humidity_command_topic: "echonetlite2mqtt/elapi/v2/devices/master_bedroom_ac/properties/set"
      target_humidity_command_template: >-
        { "humidificationLevel":"{{ ((value / 5) - 7) | round }}" }
```

This gets represented as a switch with a humidity slider in HA:
![IMG_C9D43D3E77E7-1](https://user-images.githubusercontent.com/5618675/227934649-6422e161-76e4-4075-9970-9f96c5a95cea.jpeg)

The problem is that sometimes, flipping the switch to ON doesn't work. I can verify that the MQTT properties are being set:

```
11405	2023-03-27 20:48:09	[MQTT] prop changed: master_bedroom_ac humidifierFunction on
11404	2023-03-27 20:48:09	[MQTT] prop changed: master_bedroom_ac operationMode circulation
11403	2023-03-27 20:48:09	[MQTT] prop changed: master_bedroom_ac operationStatus true
```

But it looks like maybe the AC is sometimes _not_ applying the `humidifierFunction` successfully:

```
11408	2023-03-27 20:48:10	[ECHONETLite] prop changed: master_bedroom_ac airFlowLevel auto
11407	2023-03-27 20:48:10	[ECHONETLite] prop changed: master_bedroom_ac operationMode circulation
11406	2023-03-27 20:48:10	[ECHONETLite] prop changed: master_bedroom_ac operationStatus true
```

I believe if `operationMode` _isn't_ set to `circulation` first, then `humidifierFunction` can't turn to `on`.

If I had to guess, the AC isn't applying multiple echonetlite properties atomically. It's probably just applying each in a random order, so if it attempts to apply `humidifierFunction` _before_ applying `operationMode`, it fails to do so. This causes the above MQTT Humidifier's switch to evaluate to `off`.

I'm not exactly sure how to solve this via just the current echonetlite2mqtt. It seems like I might have to write an automation that listens for a custom topic, then does a sequence of property `set`s on the unit. 

Here are my logs:

[echonetlite2mqtt_logs_internalsStatus-4.zip](https://github.com/banban525/echonetlite2mqtt/files/11078284/echonetlite2mqtt_logs_internalsStatus-4.zip)
