### ISSUE TITLE
Throttling MQTT Set Requests

### ISSUE THREAD

**Issue by aftertommy** [banban525/echonetlite2mqtt#21]
Now that I’ve got the WTY2001 bridging between LinkPlus and echonetlite, I’m finally able to control my lights via HomeAssistant. 

Unfortunately, it seems like the WTY2001 struggles with setting multiple devices at the same time. If I try to turn off all the lights in the kitchen (my kitchen has 3 separate lights), the WTY2001 appears to ignore at least 1 of the lights each time, though the specific light that doesn’t turn off is different every time. 

I’ve confirmed in the echonetlite2mqtt logs that these requests _are_ going through. I suspect the WTY2001 needs time between each request. 

Is there any way to throttle individual requests in echonetlite2mqtt? The echonetlite guidelines (Part V, 1.7) state that throttling may be required for certain devices if waiting for a response doesnt resolve issues of dropped requests. Does echonetlite2mqtt do any of this already?

**Comment by aftertommy** [comment]
I’ve attached my logs to this. You’ll see the most recent logs where I am constantly turning on and off lights in the kitchen, and though the request is sent it’s not always handled. 

[echonetlite2mqtt_logs_internalsStatus 3.zip](https://github.com/banban525/echonetlite2mqtt/files/12826554/echonetlite2mqtt_logs_internalsStatus.3.zip)

**Comment by aftertommy** [comment]
> Did you operate the three lights kitchen_down_lights , kitchen_island_down_lights and pantry_light ?

That is correct. 

> (2) Add a wait time between commands in applications that send commands, such as Home Assistant.

Unfortunately I don’t believe this is possible without a lot of work and indirection. Home Assistant is using the MQTT light platform to control these devices, and I don’t believe there’s any way to delay between commands. 

> I am adopting this.

What do you mean?


I can try to increase the wait interval — I thought that was only for discovering devices. It’s unfortunate that this is a global value, as the lights are the only ones that struggle with responding in time. I use plenty of other devices too, and their interactions would slow down as well by adjusting this wait time. 

Just to confirm, are you waiting for a result from the echonetlite node before sending the next command?

**Comment by banban525** [comment]
> Just to confirm, are you waiting for a result from the echonetlite node before sending the next command?

No, echonetlite2mqtt is not waiting for command responses. 
it only sends commands at regular intervals.

I know there are problems with this method.
However, this problem is difficult to fix because it is a method of a library echonet-lite.js.

>> I am adopting this.
>
> What do you mean?

If you're using Home Assistant, I think you can implement it using scripts and the delay command.
but it might be difficult for some people.

**Comment by aftertommy** [comment]
Thank you for your reply.

I increased `ECHONET_INTERVAL_TO_GET_PROPERTIES` to `5000` just as a test, and then tried turning on two lights at the same time via MQTT. Even though I would expect each light to turn on about 5 seconds apart, they appear to turn on at the same time (when it works). Are you sure that `echonetlite2mqtt` is waiting `ECHONET_INTERVAL_TO_GET_PROPERTIES` between each echonetlite set request it's sending out? It seems like it's sending the requests out simultaneously.

In the attached log, I had tried to turn on `office_ceiling_light` and `office_indirect_light`. I would expect one to turn on, then 5 seconds later for the second to turn on, but they both appeared to turn on at the same time. (Most of the time, only one turns on successfully, for reasons I described above.)

[echonetlite2mqtt_logs_internalsStatus-2.zip](https://github.com/banban525/echonetlite2mqtt/files/12836006/echonetlite2mqtt_logs_internalsStatus-2.zip)

**Comment by aftertommy** [comment]
In the meantime, I've set up this automation in Home Assistant to listen to a special `throttle` topic for my light set commands. It delays for a short amount of time, then republishes the payload to the normal `echonetlite2mqtt` topic for the device.

```
alias: "Echonetlite Lights: Throttle"
description: ""
trigger:
  - platform: mqtt
    topic: >-
      echonetlite2mqtt/elapi/v2/devices/throttle/+/properties/operationStatus/set
  - platform: mqtt
    topic: echonetlite2mqtt/elapi/v2/devices/throttle/+/properties/lightLevel/set
condition: []
action:
  - delay:
      hours: 0
      minutes: 0
      seconds: 0
      milliseconds: 400
  - service: mqtt.publish
    data:
      qos: 1
      topic: "{{ enl_publish_topic }}"
      payload: "{{ trigger.payload }}"
variables:
  enl_publish_topic: >-
    {{ 'echonetlite2mqtt/elapi/v2/devices/' ~
    '/'.join(trigger.topic.split('/')[5:]) }}
mode: queued
```

**Comment by banban525** [comment]
@aftertommy 


From the logs, ECHONET_INTERVAL_TO_GET_PROPERTIES is not set to 5000.
Maybe there's some spelling mistake?

```
{"level":"info","message":"echonetIntervalToGetProperties=400","timestamp":"2023-10-05T10:45:00.706Z"}

{"level":"info","message":"echonetIntervalToGetProperties=400","timestamp":"2023-10-06T23:06:48.290Z"}

{"level":"info","message":"echonetIntervalToGetProperties=400","timestamp":"2023-10-06T23:33:12.646Z"}

{"level":"info","message":"echonetIntervalToGetProperties=400","timestamp":"2023-10-06T23:36:08.080Z"}

{"level":"info","message":"echonetIntervalToGetProperties=400","timestamp":"2023-10-06T23:40:13.576Z"}
```

**Comment by banban525** [comment]
@aftertommy 

Do you want to turn on/off three lights at the same time with Home Assistant?
Can't you use "Template Switch" or "Template Light" ?

After creating three her MQTT lights, "Template Light" operate them.
You can implement lights that work simultaneously.

You can avoid the problem by providing a delay between lighting operations.

```
light:
  - platform: template
    lights:
      kitchen_lights:
...
        turn_on:
          - service: light.turn_on
            data: {}
            target:
              entity_id: light.kitchen_down_lights
          - delay:
              hours: 0
              minutes: 0
              seconds: 0
              milliseconds: 400
          - service: light.turn_on
            data: {}
            target:
              entity_id: light.kitchen_island_down_lights
          - delay:
              hours: 0
              minutes: 0
              seconds: 0
              milliseconds: 400
          - service: light.turn_on
            data: {}
            target:
              entity_id: light.pantry_light
```

**Comment by aftertommy** [comment]
I often need to turn off all the lights in a room. I do this through Siri on my iphone. Home Assistant allows for the same support, targeting groups of devices in zones. Making a group light for it goes against how this stuff is designed in HA and HomeKit.

**Comment by banban525** [comment]
Your problem is that multiple lights are controlled simultaneously from outside of Home Assistant, right?
In that case,Template Light cannot be used.

However, MQTT commands are published at the same time, but echonetlite2mqtt sends echonet lite commands at intervals of ECHONET_INTERVAL_TO_GET_PROPERTIES.
The correct solution seems to be for echonetlite2mqtt to wait for a command response before sending the next command.

As a temporary solution, you can use the "Hold" function created in #14.

The "Hold" feature is still a hidden feature, but is available since v2.3.0.
If you publish the following Json, echonetlite2mqtt will retry for 5 seconds until operationStatus becomes true.

```
{"operationStatus":"true","echonetlite2mqtt.hold":{"holdTime":5 "checkInterval":1}}
```

**Comment by aftertommy** [comment]
Thank you! I'll give it a try. I'm not sure what was going on with my `ECHONET_INTERVAL_TO_GET_PROPERTIES` setting -- it might be that I failed to rebuild my docker-compose container and had an old value. I think I prefer to keep the throttling automation I listed above, as I can target _only_ my echonetlite lights. I don't want to slow down interactions with my air conditioners and other devices.

What mqtt topic can I use `holdTime` with? Can I use it for _any_ topic (like `lightLevel`), or is it only for the `operationStatus` topic, or can I only use it with the general `properties` topic?

**Comment by banban525** [comment]
The ”hold” feature is available for publish to `properties/set`.

```
# work
echonetlite2mqtt/elapi/v2/devices/(device id)/properties/set
```

Not available for topics that change one property.

```
# not work
echonetlite2mqtt/elapi/v2/devices/(device id)/properties/(property)/set
```


The specifications of the Hold feature are as follows.

* Monitors the property at "checkInterval" intervals for "holdTime" time after receiving the set command.
* If it is not the specified value, ECHONETLite2MQTT send the set command to the device again.
* The unit of "holdTime" and "checkInterval" is seconds.
* If properties are changed for ECHONETLite2MQTT during "Hold", "Hold" will be released.

Please note the following points.
* During "Hold", even if the property is changed by other means, it will return to its original state.
For example, even if you turn off the physical switch during the Hold time, it will return to on.
* Since this is a hidden feature, there is a possibility that the specifications may be changed or the feature may be deleted in the feature.

**Comment by aftertommy** [comment]
Thank you so much! Things appear to be working better now. Just to confirm, can `holdTime` and `checkInterval` be floats? I'd like to check every 500 ms, if possible.

Here's an example of an MQTT light I've configured using the `hold` feature. Please note that while I still am using my own `throttle` topic, I've disabled the delay in my automation, so it's essentially the same as posting to the normal `properties/set` topic:

```yaml
    - name: "Dining Down Lights"
      command_topic: "echonetlite2mqtt/elapi/v2/devices/throttle/dining_down_light/properties/set"
      state_topic: "echonetlite2mqtt/elapi/v2/devices/dining_down_light/properties"
      command_on_template: |-
        {
          "operationStatus": "true",
          {% if brightness is not undefined %} "lightLevel": {{ brightness / 255 * 100 | int }}, {% endif %}
          "echonetlite2mqtt.hold":{"holdTime":5, "checkInterval":0.5}
        }
      command_off_template: |-
        {
          "operationStatus": "false",
          "echonetlite2mqtt.hold":{"holdTime":5, "checkInterval":0.5}
        }
      state_template: "{% if value_json.operationStatus == 'true' %} on {% else %} off {% endif %}"
      brightness_template: "{{ ((value_json.lightLevel / 100) * 255) | int }}"
      schema: template
      qos: 1
      optimistic: false
      unique_id: dining_down_lights
      device:
        identifiers: [dining_down_lights]
        suggested_area: Dining Room
        name: Dining Down Lights MQTT      
```
